version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewProjTestdfProject
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newprojtestdf.integrations:df2
  packages:
  - name: NewProjTestdfProject
    version: "2.0"
